server:
  port: 8889
spring:
  cloud:
    config:
      server:
          git:
            uri: "https://github.com/abinashmishraby/automobile-configrepo.git"
            refresh-rate: 70
  security:
    user:
     name: configadmin
     password: welcome1
     roles:
     - admin
     #for private repo access needs to generate token and use as below
     #"https://abinashmishraby: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@github.com/abinashmishraby/automobile-configrepo.git"
     #"https://github.com/abinashmishraby/automobile-configrepo.git"
